services:
  - type: web
    name: parkease
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_ADMIN_SECRET
        value: admin2026
    routes:
      - type: rewrite
        source: /admin
        destination: /admin/index.html
      - type: rewrite
        source: /login
        destination: /login/index.html
      - type: rewrite
        source: /*
        destination: /index.html
